spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/short_course
    username: postgres
    password: 089882413
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
server:
  port: 8000
logging:
  level:
    root: warn
# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger
    operations-sorter: method
application:
  fileUpload:
    clientPath: C:\Users\sochoeun_pc/OneDrive/Desktop/uploads


